### ISSUE TITLE
Moral machine label may be the wrong way around

### ISSUE THREAD

**Issue by t-tte** [ryansteed/heuristic-moral-machine#2]
Hello and thanks for the great work!

In the [example notebook](https://github.com/ryansteed/heuristic-moral-machine/blob/master/examples/moralmachine.ipynb) that uses moral machines data, it's stated that:

`Finally, let's make it easier to interpret the target variable. For each response, we know whether the user chose to save one set of characters (_int) by intervention, or save another set (_noint) by not intervening. Let's call that variable "Intervened" to indicate whether or not the user intervened (swerved the AV).`

However, in personal communication with the authors of the dataset, it's turned out that the correct interpretation of the 'Intervention' label is:

`Intervention: 0: the character would die if car stays, 1: the character would die if car swerves`

**Comment by ryansteed** [comment]
Good catch! The `Intervened` variable in the example notebook is indeed backwards (0 == saved by intervention, 1 == saved by non-intervention).

The `Saved` variable is still interpreted correctly - so only change in the results is that the "Always intervene" heuristic in [Figure 1](https://arxiv.org/pdf/2005.02342.pdf) should instead be called "Never intervene." This makes sense because the [original paper](https://www.nature.com/articles/s41586-018-0637-6) found a global preference for non-intervention - and our "Never intervene" heuristic (erroneously "Always intervene") predicts better than random on the same data.

I'll fix the variable and update the text.

Thanks, @t-tte!

**Comment by ryansteed** [comment]
@t-tte Submitted an updated version of the paper to arXiv with an acknowledgment - thanks again :)

**Comment by t-tte** [comment]
Great it helped, and thanks for the great work!
